#--------------
# Tratamento dos dados

# Transformar toneladas para kg:

#for {i in ANO} {let emissoes[i] := emissoes[i]*1000};

# Transformar MW para por unidade (p.u.):
# S_base = 100 MVA

for {a in ANO, h in HORARIO[a]} {
    let pg[a,h] := pg[a,h] / S_base;};
#--------------

# Inicialização das variáveis:

let Alpha := 0;
let Beta := 0;
let Gamma := 0;
let Omega := 0;
let Mu := -0.1;

let Alpha_L2 := 0;
let Beta_L2 := 0;
let Gamma_L2 := 0;
let Omega_L2 := 0;
let Mu_L2 := -0.1;

# Resolução do problema:

solve Regressao_Estatica;
solve Regressao_Estatica_L2

# Resultados:

# display MSE_est;
# display Alpha_est, Beta_est, Gamma_est, Omega_est, Mu_est;